// S programWindow.js
export const TOGGLE_WINDOW_MAX = 'TOGGLE_WINDOW_MAX'
export const TOGGLE_WINDOW_MIN = 'TOGGLE_WINDOW_MIN'
// E programWindow.js

// S clientUpdate.js
export const TOGGLE_UPDATE_DIALOG = 'TOGGLE_UPDATE_DIALOG'
export const SET_UPDATE_URL = 'SET_UPDATE_URL'
export const SET_UPDATE_VERSION = 'SET_UPDATE_VERSION'
export const SET_UPDATE_NOTES = 'SET_UPDATE_NOTES'
export const SET_UPDATE_PUB_DATE = 'SET_UPDATE_PUB_DATE'
export const SET_KEEP_VERSION_STATUS = 'SET_KEEP_VERSION_STATUS'
export const SET_HAS_NEW_STATUS = 'SET_HAS_NEW_STATUS'
// E clientUpdate.js

// S excel.js
export const SET_EXCEL_BASE_INFO = 'SET_EXCEL_BASE_INFO'
export const SET_ACTIVE_SHEET = 'SET_ACTIVE_SHEET'
export const SET_FILTER_DATA = 'SET_FILTER_DATA'
// E excel.js

// S File.js
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE'
export const SET_UPLOAD_FILES = 'SET_UPLOAD_FILES'
export const DEL_UPLOAD_FILES = 'DEL_UPLOAD_FILES'
export const SET_UPLOAD_STATUS = 'SET_UPLOAD_STATUS'
// E File.js

// S filter.js
export const ADD_FILTER = 'ADD_FILTER'
export const DEL_FILTER = 'DEL_FILTER'
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA'
export const SET_FILTER_WAY = 'SET_FILTER_WAY'
export const TOGGLE_FILTER_PANEL_STATUS = 'TOGGLE_FILTER_PANEL_STATUS'
export const SET_COL_SELECT_DIALOG_STATUS = 'SET_COL_SELECT_DIALOG_STATUS'
export const SET_COL_SELECT_TYPE = 'SET_COL_SELECT_TYPE'
export const INIT_FILTER_TAG_LIST = 'INIT_FILTER_TAG_LIST'
// E filter.js

// S unique.js
export const SET_UNIQUE_COLS = 'SET_UNIQUE_COLS'
export const INIT_UNIQUE = 'INIT_UNIQUE'
// E unique.js